# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Herigstad Lab
tagline:          Physiology in an air-polluted world
url:              https://mariherigstad.github.io
shorturl:         mariherigstad.github.io

author:
  name:           'Herigstad Lab'
  url:            https://mariherigstad.github.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/mariherigstad/mariherigstad.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Research: '/research/'
  Papers: '/papers/'
  People: '/people/'
  Study: '/study'
  News: '/news'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
